"\"\"\""
"CCA AI Assistant Package"
"\"\"\""
""
"from app.main import app"
"from app.config import config"
"from app.database import Database"
"from app.models import QuestionRequest, QuestionResponse"
""
"__version__ = '0.1.0'"
"__all__ = ['app', 'config', 'Database', 'QuestionRequest', 'QuestionResponse']"
